name: COVID-19 Equity report

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # This will happen once a day at 00 hours.

jobs:
  build:
    runs-on: Ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull rocker/tidyverse:4.1.0

      ##################################################################
      # YOU ONLY NEED TO CHANGE THIS BIT -------------------------------
      - name: Render
        run:  |
          cd 01-covid-equity
          docker run -v$(pwd):/home/report -w/home/report \
            rocker/tidyverse:4.1.0 \
            Rscript -e 'rmarkdown::render("README.Rmd")'
      ##################################################################

      - name: Commit results
        run: |
          cd 01-covid-equity
          git add README_files/figure-gfm/* 
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -a -m 'Updating the COVID-19 equity report' || echo Nothing has changed
          git push origin || echo "No changes to commit" 
